export enum RTC_MESSAGE_REASON {
  // CONNECTION STUFF
  AHOY,
  CONNECTION_INITIATION,
  RELAY_SIGNAL,
  SIGNAL,
  CONNECTION_COUNT_CHECK,

  // DATA STUFF
  UPLOAD,
  UPLOAD_RESPONSE,
  DOWNLOAD,
  DOWNLOAD_RESPONSE,
  REDIRECTION,
  REPORT
};