export enum RTC_MESSAGE_REASON {
  // CONNECTION STUFF
  AHOY,
  CONNECTION_INITIATION,
  RELAY_SIGNAL,
  SIGNAL,
  CONNECTION_COUNT_CHECK,

  // DATA STUFF
  HASH_REQUEST,
  HASH_RESPONSE,
  HASH_UPLOAD,
  HASH_UPLOAD_RESPONSE,
  HASH_REDIRECTION
};